# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: "scripts/kind-config.yaml"
          version: "v0.12.0"
          kubectl_version: "v1.23.4"

      - name: kubectl
        run: |
          kubectl get node
          cat $HOME/.kube/config
          docker ps

