name: macOS Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker
        if: startsWith(matrix.os, 'macos' )
        uses: docker-practice/actions-setup-docker@master
      - name: docker version
        run: |
          docker version
