name: macOS Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:

      - name: docker
        run: |
          docker version
